### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/proc/cpuinfo'

### ISSUE THREAD

**Issue by lashwor1** [adafruit/Adafruit_CircuitPython_MAX31856#14]
Hey, 

I'm having issues with stability while running this library. At first I thought it was my code that was opening files and not closing properly but after removing my code and running the simple example code for the lib in a while loop, I still got an OSError: [Errno 24] Too many open files: for '/proc/cpuinfo'. I'm not sure if this code is meant to work in a continues loop or just perform single executions. My project requires continuous temperature monitoring and I have look high and low for a solution or work around. I'd appreciate your input and help.

Below is the test loop using the sample code and the error message:

 #!/usr/bin/env python

import adafruit_max31856
import board
import digitalio

while True:
    # Create sensor object, communicating over the board's default SPI bus
    spi = board.SPI()

    # allocate a CS pin and set the direction
    cs = digitalio.DigitalInOut(board.D5)
    cs.direction = digitalio.Direction.OUTPUT

    # create a thermocouple object with the above
    thermocouple = adafruit_max31856.MAX31856(spi, cs)

    # set thermocouple object as temp integer variable
    temp =int(thermocouple.temperature) 
    # print the temperature!
    print(temp)

Traceback (most recent call last):
  File "/home/pi/Desktop/Project_Code/Main_Code/temp_continuous.py", line 15, in <module>
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/adafruit_max31856.py", line 153, in __init__
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/adafruit_max31856.py", line 293, in _write_u8
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/adafruit_bus_device/spi_device.py", line 76, in __enter__
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/busio.py", line 282, in configure
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/adafruit_platformdetect/board.py", line 484, in any_raspberry_pi
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/adafruit_platformdetect/board.py", line 217, in _pi_rev_code
  File "/home/pi/Enviroments/K_Therms/lib/python3.7/site-packages/adafruit_platformdetect/__init__.py", line 51, in get_cpuinfo_field
OSError: [Errno 24] Too many open files: '/proc/cpuinfo'

**Comment by tannewt** [comment]
For technical support please post on the support forum: https://forums.adafruit.com/viewforum.php?f=60

(I suspect you need to do object initialization outside of your `while True:` loop.)
